anthropic_apikey="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"
openai_apikey="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"
anyscale_apikey="esecret_u5zzg1keygc9gt3nt3ip4h1f8w"